# =========================
# TOKYONIGHT - HYPRLOCK THEME
# =========================

background {
    monitor =
    path = /home/Arch/Downloads/Wallpaper/tokyonight.png
    color = rgba(36, 34, 42, 1.0)

    blur_passes = 0.5
    blur_size = 7
}

# =========================
# TIME
# =========================
label {
    monitor =
    text = $TIME
    color = rgb(7fa2e4)
    font_size = 90
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 100, 100
    halign = left
    valign = bottom
}

# =========================
# DATE
# =========================
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgba(166, 176, 212, 0.7)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 105, 230
    halign = left
    valign = bottom
}

# =========================
# INPUT FIELD
# =========================
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgb(7fa2e4)
    inner_color = rgb(24202a)
    font_color = rgb(a6b0d4)

    fade_on_empty = false
    rounding = -1

    check_color = rgb(7fa2e4)
    fail_color = rgb(ff4841)

    placeholder_text = <span foreground="##a6b0d4" weight="bold">    System Active - $USER</span>

    hide_input = false
    position = -100, 100
    halign = right
    valign = bottom
}
