# =========================
# PURPLE - KITTY THEME (REFINED SYSTEM FORMAT)
# =========================

# --- Fonts & Style ---
font_family      JetBrainsMono Nerd Font
font_size        12.0
window_padding_width 27

background_opacity 0.5
dynamic_background_opacity yes

# --- Colors ---
background            #0d0612
foreground            #cba6f7

selection_background  #cba6f7
selection_foreground  #0d0612

# Dim tones (purple system depth)
color8   #11091a
color7   #cba6f7

# Primary purple identity
color5   #cba6f7
color13  #cba6f7

# Slight variation purple palette (intentional repetition like Neoncore)
color0   #cba6f7
color1   #cba6f7
color2   #cba6f7
color3   #cba6f7
color4   #cba6f7   # Arch logo icon color
color6   #cba6f7
color7   #cba6f7
color8   #cba6f7   # text color

# --- Cursor ---
cursor                #cba6f7
cursor_text_color     #cba6f7
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

# Adds a smooth, fading trail behind the moving pipe cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #cba6f7
active_tab_foreground   #0d0612
inactive_tab_background #11091a
inactive_tab_foreground #cba6f7
