# Neoncore Theme Variables

$active_border = rgb(ff4d6d)
$inactive_border = rgba(111111aa)

$gaps_in = 5
$gaps_out = 20

$radius = 15
$blur = 7

$active_opacity = 1.0
$inactive_opacity = 0.9

$shadow_color = rgba(ff4d6d1a)
