background {
    monitor =
    path = /home/Arch/Downloads/Wallpaper/neoncore1.jpg
    color = rgba(15, 8, 10, 1.0)

    blur_passes = 0.5
    blur_size = 7
}

# TIME
label {
    monitor =
    text = $TIME
    color = rgb(ff4d6d)
    font_size = 90
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 100, 100
    halign = left
    valign = bottom
}

# DATE
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgba(ff4d6dcc)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 105, 230
    halign = left
    valign = bottom
}

# INPUT FIELD
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgb(ff4d6d)
    inner_color = rgb(0f080a)
    font_color = rgb(ff4d6d)

    fade_on_empty = false
    rounding = -1

    check_color = rgb(ff9e64)
    fail_color = rgb(ff3355)

    placeholder_text = <span foreground="##ff4d6d">    Logged in as $USER</span>

    hide_input = false
    position = -100, 100
    halign = right
    valign = bottom
}
