#Violetcore Theme Variables

$active_border = rgb(cba6f7)
$inactive_border = rgba(0d0612aa)

$gaps_in = 5
$gaps_out = 20

$radius = 15
$blur = 7

$active_opacity = 1
$inactive_opacity = 0.9

$shadow_color = rgba(cba6f71a)
