# =========================
# MONOCHROME ASH - HYPRLOCK
# =========================

background {
    monitor =
    path = /home/Arch/Downloads/Wallpaper/monochrome1.jpg
    color = rgba(0, 0, 0, 1.0)

    blur_passes = 0.5
    blur_size = 7
}

# =========================
# TIME
# =========================
label {
    monitor =
    text = $TIME
    color = rgb(a7a7a7)
    font_size = 90
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 100, 100
    halign = left
    valign = bottom
}

# =========================
# DATE
# =========================
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgba(179, 179, 179, 0.7)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 105, 230
    halign = left
    valign = bottom
}

# =========================
# INPUT FIELD
# =========================
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true

    outer_color = rgb(272727)
    inner_color = rgb(000000)
    font_color = rgb(b3b3b3)

    fade_on_empty = false
    rounding = -1

    check_color = rgb(a7a7a7)
    fail_color = rgb(9e9e9e)

    placeholder_text = <span foreground="##b3b3b3" weight="bold">    System Active - $USER</span>

    hide_input = false
    position = -100, 100
    halign = right
    valign = bottom
}
