background {
    monitor =
    path = /home/Arch/Downloads/Wallpaper/2.jpeg   # Make sure this path is exactly right
    color = rgba(13, 6, 18, 1.0)
    
    # This blurs the wallpaper slightly so the text is easier to read
    blur_passes = 0.5
    blur_size = 7
}


# TIME (Bottom Left)
label {
    monitor =
    text = $TIME
    color = rgb(cba6f7)
    font_size = 90
    font_family = JetBrainsMono Nerd Font ExtraBold
    position = 100, 100
    halign = left
    valign = bottom
}

# DATE (Just above the time)
label {
    monitor =
    text = cmd[update:43200000] echo "$(date +"%A, %d %B")"
    color = rgba(203, 166, 247, 0.7)
    font_size = 20
    font_family = JetBrainsMono Nerd Font
    position = 105, 230
    halign = left
    valign = bottom
}

# INPUT FIELD (Bottom Right - Matching your Waybar Pills)
input-field {
    monitor =
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgb(cba6f7)
    inner_color = rgb(0d0612)
    font_color = rgb(cba6f7)
    fade_on_empty = false
    rounding = -1 # Makes it a perfect pill
    check_color = rgb(fab387) # Orange when checking password
    fail_color = rgb(f38ba8) # Red on wrong password
    placeholder_text = <span foreground="##cba6f7">    Logged in as $USER</span>
    hide_input = false
    position = -100, 100
    halign = right
    valign = bottom
}

