# =========================
# NEONCORE - KITTY THEME (REFINED)
# =========================

# --- Fonts & Style ---
font_family      JetBrainsMono Nerd Font
font_size        12.0
window_padding_width 27

background_opacity 0.5
dynamic_background_opacity yes

# --- Colors ---
background            #111111
foreground            #ff4d6d

selection_background  #ff4d6d
selection_foreground  #111111

# Dim tones (neutral dark red system)
color8   #2a2a2a
color7   #e0e0e0

# Primary neon red identity
color5   #ff4d6d
color13  #ff4d6d

# Slight variation red palette (system depth)
color0   #ff4d6d
color1   #ff4d6d
color2   #ff4d6d
color3   #ff4d6d
color4   #ff4d6d  #Arch logo icon color
color6   #ff6b6b
color7   #ff4d6d
color8   #ff4d6d  #text color

# --- Cursor ---
cursor                #ff4d6d
cursor_text_color     #ff4d6d
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

# Adds a smooth, fading trail behind the moving pipe cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #ff4d6d
active_tab_foreground   #ff4d6d
inactive_tab_background #ff4d6d
inactive_tab_foreground #ff4d6d
