# ==========================================
# TOKYONIGHT - CYBERCREAM EDITION (KITTY)
# ==========================================

# --- Fonts & Style ---
font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.5
dynamic_background_opacity  yes

# --- Primary Canvas ---
background            #24202A
foreground            #A6B0D4
selection_background  #A6B0D4
selection_foreground  #24202A

# --- Cursor ---
cursor                #7FA2E4
cursor_text_color     #24202A
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

# Adds a smooth, fading trail behind the moving pipe cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #7FA2E4
active_tab_foreground   #24202A
inactive_tab_background #24202A
inactive_tab_foreground #A6B0D4

# --- Color Palette (TokyoNight Inspired) ---

# Black / Dark Grey
color0   #24202A
color8   #4B5263

# Red
color1   #ff4841
color9   #ff6b6b

# Green
color2   #A2C866
color10  #b7d98a

# Yellow
color3   #FEFE9B
color11  #fff3b0

# Blue (Primary Accent)
color4   #7FA2E4
color12  #9bbcf0

# Magenta
color5   #AFAFD1
color13  #c7c7e6

# Cyan
color6   #69F8FC
color14  #9ef7ff

# White / Text
color7   #A6B0D4
color15  #ffffff
