# ==========================================
# MONOCHROME ASH (MATCHES WAYBAR)
# ==========================================

# --- Fonts & Style ---
font_family          JetBrainsMono Nerd Font
font_size            12.0
window_padding_width 27

background_opacity          0.8
dynamic_background_opacity  yes

# --- Primary Canvas ---
background            #000000
foreground            #B3B3B3
selection_background  #A7A7A7
selection_foreground  #000000

# --- Cursor ---
cursor                #A7A7A7
cursor_text_color     #000000
cursor_shape          beam
cursor_beam_thickness 5.0
cursor_blink_interval 0.5

# Adds a smooth, fading trail behind the moving pipe cursor
cursor_trail 3
cursor_trail_decay 0.1 0.4

# --- Tabs ---
active_tab_background   #A7A7A7
active_tab_foreground   #000000
inactive_tab_background #1A1A1A
inactive_tab_foreground #9E9E9E

# ==========================================
# TERMINAL PALETTE
# ==========================================

# Black / Bright Black
color0   #000000
color8   #5C5C5C

# Red
color1   #9E9E9E
color9   #B0B0B0

# Green
color2   #AAAAAA
color10  #C0C0C0

# Yellow
color3   #A7A7A7
color11  #D0D0D0

# Blue
color4   #B3B3B3
color12  #D6D6D6

# Magenta
color5   #A7A7A7
color13  #D0D0D0

# Cyan
color6   #B0B0B0
color14  #D6D6D6

# White / Bright White
color7   #C9C7C7
color15  #FFFFFF

# URL underline color
url_color #A7A7A7

# Window border
active_border_color   #272727
inactive_border_color #000000

# Bell
visual_bell_color #A7A7A7
